### ISSUE TITLE
Sign Out link is partially blocked in the Menu

### ISSUE THREAD

**Issue by jlcortsa** [barbacenasmc/skosay#1]
Description:

The Sign Out link is partially hidden by the header (not completely shown) in the hamburger menu. See image # 2 below. This bug was originally sent by Jason via text message. See attached screenshots.

Steps to Replicate: 
1. Go to app.skosay.com
2. Sign-in
3. Click the hamburger menu.

Actual Result: The "Sign Out" link is not completely shown.
Expected Result: It should completely show "Sign Out" in the hamburger menu. 
Other Details: The bug was encountered using Samsung S3. 

Attachments:
![image1](https://cloud.githubusercontent.com/assets/12255189/7475163/8f8044f8-f30b-11e4-908e-f4f1e9a30b34.JPG)

![image2](https://cloud.githubusercontent.com/assets/12255189/7475162/8f7ece16-f30b-11e4-89bd-c9127e536078.JPG)

**Comment by shielanunez** [comment]
Hi Sir @jlcortsa , I would like to ask what browser did you use to replicate this issue?

**Comment by jlcortsa** [comment]
It seems like Chrome by just looking at it. It is also on a Samsung S3. 

Thanks

**Comment by shielanunez** [comment]
Thanks Sir Jay. But isn't it a native android web browser? I tried to compare the UI of the browser to different browsers that I have on my device and it looks similar to the native web browser than Chrome. On our end, we can replicate the issue when using the native web browser. I still have to check on which specific OS version it can be replicated.

**Comment by jlcortsa** [comment]
From Jason: "Android 4.3 and the browser was just the internet app.  dont think it was chrome unless it is the one embedded is chrome.  it just says internet."

**Comment by jlcortsa** [comment]
From Jason: "android 4.3 and the browser was just the internet app.  dont think it was chrome unless it is the one embedded is chrome.  it just says internet.".

**Comment by srirussel** [comment]
Rosey solved this one
