### ISSUE TITLE
"No message left by customer" is being displayed in the chat screen

### ISSUE THREAD

**Issue by jlcortsa** [barbacenasmc/skosay#2]
Jason reported this issue. Sometimes the "No message left by customer" is displayed instead of the actual message. See attached files:

https://www.dropbox.com/s/nw3zpecrsk17tbz/Photo%20May%2011%2C%203%2009%2016%20PM.png?dl=0

https://www.dropbox.com/s/6ayu7mabba58pbk/Photo%20May%2011%2C%203%2009%2019%20PM.png?dl=0

I modified this today because the NSAA event is today. I just commented out the else-statement on message.blade.php. But now an empty message is displayed (only the bubble is displayed without a message).

Please figure out why this is being displayed and fix it.

Thanks

**Comment by srirussel** [comment]
I see the error sir since you only have one question answerable by yes or no. Our current code was only getting up to array[3] of a message. I already fix this issue!
